using Terraria;
using Terraria.ID;
using Terraria.ModLoader;
using Microsoft.Xna.Framework;
using ShaderLib;
using DyeHard.Shaders;

namespace DyeHard
{
	class DyeHard : Mod
	{
		public override void Load()
		{
			ShaderLoader.RegisterMod(this);
			Config.Load();
			if (Main.netMode != NetmodeID.Server)
			{
				//- colored -//
				
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("CottonCandyBlue", "ArmorColored", new Vector3(0.34f, 0.72f, 1f), 1.2f), this, ItemType("CottonCandyBlueDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("CottonCandyPink", "ArmorColored", new Vector3(1f, 0.55f, 0.8f), 1.3f), this, ItemType("CottonCandyPinkDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("RottenBrown", "ArmorColored", new Vector3(0.62f, 0.35f, 0.40f)), this, ItemType("RottenBrownDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("RottenGreen", "ArmorColored", new Vector3(0.58f, 0.63f, 0.13f), 1.2f), this, ItemType("RottenGreenDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("VilePurple", "ArmorColored", new Vector3(0.56f, 0.43f, 0.81f), 1.2f), this, ItemType("VilePurpleDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("ShadowPurple", "ArmorColored", new Vector3(0.26f, 0.13f, 0.71f), 1.2f), this, ItemType("ShadowPurpleDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("GrossBrown", "ArmorColored", new Vector3(0.70f, 0.35f, 0.12f)), this, ItemType("GrossBrownDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("GrossPink", "ArmorColored", new Vector3(1f, 0.5f, 0.5f), 1.3f), this, ItemType("GrossPinkDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("ViciousRed", "ArmorColored", new Vector3(0.8f, 0.3f, 0.3f), 1.2f), this, ItemType("ViciousRedDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("FleshRed", "ArmorColored", new Vector3(0.9f, 0.15f, 0.15f), 1.2f), this, ItemType("FleshRedDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("ShiftingRainbow", "ArmorColored", 1.2f, 0, 0), this, ItemType("ShiftingRainbowDye"));
				//- Bright -//
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightRottenBrown", "ArmorColored", new Vector3(0.62f * 0.5f + 0.5f, 0.35f * 0.5f + 0.5f, 0.40f * 0.5f + 0.5f)), this, ItemType("BrightRottenBrownDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightRottenGreen", "ArmorColored", new Vector3(0.58f * 0.5f + 0.5f, 0.63f * 0.5f + 0.5f, 0.13f * 0.5f + 0.5f), 1.2f), this, ItemType("BrightRottenGreenDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightVilePurple", "ArmorColored", new Vector3(0.56f * 0.5f + 0.5f, 0.43f * 0.5f + 0.5f, 0.81f * 0.5f + 0.5f), 1.2f), this, ItemType("BrightVilePurpleDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightShadowPurple", "ArmorColored", new Vector3(0.26f * 0.5f + 0.5f, 0.13f * 0.5f + 0.5f, 0.71f * 0.5f + 0.5f), 1.2f), this, ItemType("BrightShadowPurpleDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightGrossBrown", "ArmorColored", new Vector3(0.70f * 0.5f + 0.5f, 0.35f * 0.5f + 0.5f, 0.12f * 0.5f + 0.5f)), this, ItemType("BrightGrossBrownDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightGrossPink", "ArmorColored", new Vector3(1f * 0.5f + 0.5f, 0.5f * 0.5f + 0.5f, 0.5f * 0.5f + 0.5f), 1.3f), this, ItemType("BrightGrossPinkDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightViciousRed", "ArmorColored", new Vector3(0.8f * 0.5f + 0.5f, 0.3f * 0.5f + 0.5f, 0.3f * 0.5f + 0.5f), 1.2f), this, ItemType("BrightViciousRedDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightFleshRed", "ArmorColored", new Vector3(0.9f * 0.5f + 0.5f, 0.15f * 0.5f + 0.5f, 0.15f * 0.5f + 0.5f), 1.2f), this, ItemType("BrightFleshRedDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightBlack", "ArmorBrightnessColored", new Vector3(0.6f * 0.5f + 0.5f, 0.6f * 0.5f + 0.5f, 0.6f * 0.5f + 0.5f)), this, ItemType("BrightBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("BrightShiftingRainbow", "ArmorColored", 1.2f, 0, 1), this, ItemType("BrightShiftingRainbowDye"));
				//- Dim -//
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimRed", "ArmorColored", new Vector3(1f * 0.5f, 0f * 0.5f, 0f * 0.5f), 1.2f), this, ItemType("DimRedDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimOrange", "ArmorColored", new Vector3(1f * 0.5f, 0.5f * 0.5f, 0f * 0.5f), 1.2f), this, ItemType("DimOrangeDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimYellow", "ArmorColored", new Vector3(1f * 0.5f, 1f * 0.5f, 0f * 0.5f), 1.2f), this, ItemType("DimYellowDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimLime", "ArmorColored", new Vector3(0.5f * 0.5f, 1f * 0.5f, 0f * 0.5f), 1.2f), this, ItemType("DimLimeDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimGreen", "ArmorColored", new Vector3(0f * 0.5f, 1f * 0.5f, 0f * 0.5f), 1.2f), this, ItemType("DimGreenDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimTeal", "ArmorColored", new Vector3(0f * 0.5f, 1f * 0.5f, 0.5f * 0.5f), 1.2f), this, ItemType("DimTealDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimCyan", "ArmorColored", new Vector3(0f * 0.5f, 1f * 0.5f, 1f * 0.5f), 1.2f), this, ItemType("DimCyanDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimSkyBlue", "ArmorColored", new Vector3(0.2f * 0.5f, 0.5f * 0.5f, 1f * 0.5f), 1.2f), this, ItemType("DimSkyBlueDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimBlue", "ArmorColored", new Vector3(0f * 0.5f, 0f * 0.5f, 1f * 0.5f), 1.2f), this, ItemType("DimBlueDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimPurple", "ArmorColored", new Vector3(0.5f * 0.5f, 0f * 0.5f, 1f * 0.5f), 1.2f), this, ItemType("DimPurpleDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimViolet", "ArmorColored", new Vector3(1f * 0.5f, 0f * 0.5f, 1f * 0.5f), 1.2f), this, ItemType("DimVioletDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimPink", "ArmorColored", new Vector3(1f * 0.5f, 0.1f * 0.5f, 0.5f * 0.5f), 1.3f), this, ItemType("DimPinkDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimBrown", "ArmorColored", new Vector3(0.4f * 0.5f, 0.2f * 0.5f, 0f * 0.5f), 1f), this, ItemType("DimBrownDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimBlack", "ArmorBrightnessColored", new Vector3(0.6f * 0.5f, 0.6f * 0.5f, 0.6f * 0.5f)), this, ItemType("DimBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimSilver", "ArmorBrightnessColored", new Vector3(1f * 0.5f, 1f * 0.5f, 1f * 0.5f), 1.2f), this, ItemType("DimSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimRottenBrown", "ArmorColored", new Vector3(0.62f * 0.5f, 0.35f * 0.5f, 0.40f * 0.5f)), this, ItemType("DimRottenBrownDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimRottenGreen", "ArmorColored", new Vector3(0.58f * 0.5f, 0.63f * 0.5f, 0.13f * 0.5f), 1.2f), this, ItemType("DimRottenGreenDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimVilePurple", "ArmorColored", new Vector3(0.56f * 0.5f, 0.43f * 0.5f, 0.81f * 0.5f), 1.2f), this, ItemType("DimVilePurpleDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimShadowPurple", "ArmorColored", new Vector3(0.26f * 0.5f, 0.13f * 0.5f, 0.71f * 0.5f), 1.2f), this, ItemType("DimShadowPurpleDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimGrossBrown", "ArmorColored", new Vector3(0.70f * 0.5f, 0.35f * 0.5f, 0.12f * 0.5f)), this, ItemType("DimGrossBrownDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimGrossPink", "ArmorColored", new Vector3(1f * 0.5f, 0.5f * 0.5f, 0.5f * 0.5f), 1.3f), this, ItemType("DimGrossPinkDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimViciousRed", "ArmorColored", new Vector3(0.8f * 0.5f, 0.3f * 0.5f, 0.3f * 0.5f), 1.2f), this, ItemType("DimViciousRedDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimFleshRed", "ArmorColored", new Vector3(0.9f * 0.5f, 0.15f * 0.5f, 0.15f * 0.5f), 1.2f), this, ItemType("DimFleshRedDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("DimShiftingRainbow", "ArmorColored", 1.2f, 0, 2), this, ItemType("DimShiftingRainbowDye"));
				//- coloredandblack -//
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BlackandBlack", "ArmorColoredAndBlack", new Vector3(0.6f, 0.6f, 0.6f)), this, ItemType("BlackandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightRedandBlack", "ArmorColoredAndBlack", new Vector3(1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), 1.2f), this, ItemType("BrightRedandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightOrangeandBlack", "ArmorColoredAndBlack", new Vector3(1f * 0.5f + 0.5f, 0.5f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), 1.2f), this, ItemType("BrightOrangeandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightYellowandBlack", "ArmorColoredAndBlack", new Vector3(1f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), 1.2f), this, ItemType("BrightYellowandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightLimeandBlack", "ArmorColoredAndBlack", new Vector3(0.5f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), 1.2f), this, ItemType("BrightLimeandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightGreenandBlack", "ArmorColoredAndBlack", new Vector3(0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), 1.2f), this, ItemType("BrightGreenandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightTealandBlack", "ArmorColoredAndBlack", new Vector3(0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0.5f * 0.5f + 0.5f), 1.2f), this, ItemType("BrightTealandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightCyanandBlack", "ArmorColoredAndBlack", new Vector3(0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 1f * 0.5f + 0.5f), 1.2f), this, ItemType("BrightCyanandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightSkyBlueandBlack", "ArmorColoredAndBlack", new Vector3(0.2f * 0.5f + 0.5f, 0.5f * 0.5f + 0.5f, 1f * 0.5f + 0.5f), 1.2f), this, ItemType("BrightSkyBlueandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightBlueandBlack", "ArmorColoredAndBlack", new Vector3(0f * 0.5f + 0.5f, 0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f), 1.2f), this, ItemType("BrightBlueandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightPurpleandBlack", "ArmorColoredAndBlack", new Vector3(0.5f * 0.5f + 0.5f, 0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f), 1.2f), this, ItemType("BrightPurpleandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightVioletandBlack", "ArmorColoredAndBlack", new Vector3(1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f), 1.2f), this, ItemType("BrightVioletandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightPinkandBlack", "ArmorColoredAndBlack", new Vector3(1f * 0.5f + 0.5f, 0.1f * 0.5f + 0.5f, 0.5f * 0.5f + 0.5f), 1.3f), this, ItemType("BrightPinkandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightBrownandBlack", "ArmorColoredAndBlack", new Vector3(0.4f * 0.5f + 0.5f, 0.2f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), 1f), this, ItemType("BrightBrownandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightBlackandBlack", "ArmorColoredAndBlack", new Vector3(0.6f * 0.5f + 0.5f, 0.6f * 0.5f + 0.5f, 0.6f * 0.5f + 0.5f)), this, ItemType("BrightBlackandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightSilverandBlack", "ArmorColoredAndBlack", new Vector3(1.5f, 1.5f, 1.5f), 1.2f), this, ItemType("BrightSilverandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimRedandBlack", "ArmorColoredAndBlack", new Vector3(1f * 0.5f, 0f * 0.5f, 0f * 0.5f), 1.2f), this, ItemType("DimRedandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimOrangeandBlack", "ArmorColoredAndBlack", new Vector3(1f * 0.5f, 0.5f * 0.5f, 0f * 0.5f), 1.2f), this, ItemType("DimOrangeandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimYellowandBlack", "ArmorColoredAndBlack", new Vector3(1f * 0.5f, 1f * 0.5f, 0f * 0.5f), 1.2f), this, ItemType("DimYellowandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimLimeandBlack", "ArmorColoredAndBlack", new Vector3(0.5f * 0.5f, 1f * 0.5f, 0f * 0.5f), 1.2f), this, ItemType("DimLimeandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimGreenandBlack", "ArmorColoredAndBlack", new Vector3(0f * 0.5f, 1f * 0.5f, 0f * 0.5f), 1.2f), this, ItemType("DimGreenandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimTealandBlack", "ArmorColoredAndBlack", new Vector3(0f * 0.5f, 1f * 0.5f, 0.5f * 0.5f), 1.2f), this, ItemType("DimTealandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimCyanandBlack", "ArmorColoredAndBlack", new Vector3(0f * 0.5f, 1f * 0.5f, 1f * 0.5f), 1.2f), this, ItemType("DimCyanandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimSkyBlueandBlack", "ArmorColoredAndBlack", new Vector3(0.2f * 0.5f, 0.5f * 0.5f, 1f * 0.5f), 1.2f), this, ItemType("DimSkyBlueandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimBlueandBlack", "ArmorColoredAndBlack", new Vector3(0f * 0.5f, 0f * 0.5f, 1f * 0.5f), 1.2f), this, ItemType("DimBlueandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimPurpleandBlack", "ArmorColoredAndBlack", new Vector3(0.5f * 0.5f, 0f * 0.5f, 1f * 0.5f), 1.2f), this, ItemType("DimPurpleandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimVioletandBlack", "ArmorColoredAndBlack", new Vector3(1f * 0.5f, 0f * 0.5f, 1f * 0.5f), 1.2f), this, ItemType("DimVioletandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimPinkandBlack", "ArmorColoredAndBlack", new Vector3(1f * 0.5f, 0.1f * 0.5f, 0.5f * 0.5f), 1.3f), this, ItemType("DimPinkandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimBrownandBlack", "ArmorColoredAndBlack", new Vector3(0.4f * 0.5f, 0.2f * 0.5f, 0f * 0.5f), 1f), this, ItemType("DimBrownandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimBlackandBlack", "ArmorColoredAndBlack", new Vector3(0.6f * 0.5f, 0.6f * 0.5f, 0.6f * 0.5f)), this, ItemType("DimBlackandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimSilverandBlack", "ArmorColoredAndBlack", new Vector3(1f * 0.5f,1f * 0.5f,1f * 0.5f), 1.2f), this, ItemType("DimSilverandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("RottenBrownandBlack", "ArmorColoredAndBlack", new Vector3(0.62f, 0.35f, 0.40f)), this, ItemType("RottenBrownandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("RottenGreenandBlack", "ArmorColoredAndBlack", new Vector3(0.58f, 0.63f, 0.13f), 1.2f), this, ItemType("RottenGreenandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("VilePurpleandBlack", "ArmorColoredAndBlack", new Vector3(0.56f, 0.43f, 0.81f), 1.2f), this, ItemType("VilePurpleandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("ShadowPurpleandBlack", "ArmorColoredAndBlack", new Vector3(0.26f, 0.13f, 0.71f), 1.2f), this, ItemType("ShadowPurpleandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("GrossBrownandBlack", "ArmorColoredAndBlack", new Vector3(0.70f, 0.35f, 0.12f)), this, ItemType("GrossBrownandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("GrossPinkandBlack", "ArmorColoredAndBlack", new Vector3(1f, 0.5f, 0.5f), 1.3f), this, ItemType("GrossPinkandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("ViciousRedandBlack", "ArmorColoredAndBlack", new Vector3(0.8f, 0.3f, 0.3f), 1.2f), this, ItemType("ViciousRedandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("FleshRedandBlack", "ArmorColoredAndBlack", new Vector3(0.9f, 0.15f, 0.15f), 1.2f), this, ItemType("FleshRedandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("ShiftingRainbowandBlack", "ArmorColoredAndBlack", 1.2f, 0, 0), this, ItemType("ShiftingRainbowandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("BrightShiftingRainbowandBlack", "ArmorColoredAndBlack", 1.2f, 0, 1), this, ItemType("BrightShiftingRainbowandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("DimShiftingRainbowandBlack", "ArmorColoredAndBlack", 1.2f, 0, 2), this, ItemType("DimShiftingRainbowandBlackDye"));
				//- coloredandsilvertrim -//
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("SilverandSilver", "ArmorColoredAndSilverTrim", new Vector3(1f, 1f, 1f), 1.2f), this, ItemType("SilverandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightRedandSilver", "ArmorColoredAndSilverTrim", new Vector3(1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), 1.2f), this, ItemType("BrightRedandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightOrangeandSilver", "ArmorColoredAndSilverTrim", new Vector3(1f * 0.5f + 0.5f, 0.5f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), 1.2f), this, ItemType("BrightOrangeandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightYellowandSilver", "ArmorColoredAndSilverTrim", new Vector3(1f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), 1.2f), this, ItemType("BrightYellowandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightLimeandSilver", "ArmorColoredAndSilverTrim", new Vector3(0.5f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), 1.2f), this, ItemType("BrightLimeandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightGreenandSilver", "ArmorColoredAndSilverTrim", new Vector3(0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), 1.2f), this, ItemType("BrightGreenandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightTealandSilver", "ArmorColoredAndSilverTrim", new Vector3(0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0.5f * 0.5f + 0.5f), 1.2f), this, ItemType("BrightTealandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightCyanandSilver", "ArmorColoredAndSilverTrim", new Vector3(0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 1f * 0.5f + 0.5f), 1.2f), this, ItemType("BrightCyanandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightSkyBlueandSilver", "ArmorColoredAndSilverTrim", new Vector3(0.2f * 0.5f + 0.5f, 0.5f * 0.5f + 0.5f, 1f * 0.5f + 0.5f), 1.2f), this, ItemType("BrightSkyBlueandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightBlueandSilver", "ArmorColoredAndSilverTrim", new Vector3(0f * 0.5f + 0.5f, 0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f), 1.2f), this, ItemType("BrightBlueandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightPurpleandSilver", "ArmorColoredAndSilverTrim", new Vector3(0.5f * 0.5f + 0.5f, 0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f), 1.2f), this, ItemType("BrightPurpleandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightVioletandSilver", "ArmorColoredAndSilverTrim", new Vector3(1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f), 1.2f), this, ItemType("BrightVioletandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightPinkandSilver", "ArmorColoredAndSilverTrim", new Vector3(1f * 0.5f + 0.5f, 0.1f * 0.5f + 0.5f, 0.5f * 0.5f + 0.5f), 1.3f), this, ItemType("BrightPinkandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightBrownandSilver", "ArmorColoredAndSilverTrim", new Vector3(0.4f * 0.5f + 0.5f, 0.2f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), 1f), this, ItemType("BrightBrownandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightBlackandSilver", "ArmorColoredAndSilverTrim", new Vector3(0.6f * 0.5f + 0.5f, 0.6f * 0.5f + 0.5f, 0.6f * 0.5f + 0.5f)), this, ItemType("BrightBlackandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightSilverandSilver", "ArmorColoredAndSilverTrim", new Vector3(1.5f, 1.5f, 1.5f), 1.2f), this, ItemType("BrightSilverandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimRedandSilver", "ArmorColoredAndSilverTrim", new Vector3(1f * 0.5f, 0f * 0.5f, 0f * 0.5f), 1.2f), this, ItemType("DimRedandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimOrangeandSilver", "ArmorColoredAndSilverTrim", new Vector3(1f * 0.5f, 0.5f * 0.5f, 0f * 0.5f), 1.2f), this, ItemType("DimOrangeandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimYellowandSilver", "ArmorColoredAndSilverTrim", new Vector3(1f * 0.5f, 1f * 0.5f, 0f * 0.5f), 1.2f), this, ItemType("DimYellowandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimLimeandSilver", "ArmorColoredAndSilverTrim", new Vector3(0.5f * 0.5f, 1f * 0.5f, 0f * 0.5f), 1.2f), this, ItemType("DimLimeandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimGreenandSilver", "ArmorColoredAndSilverTrim", new Vector3(0f * 0.5f, 1f * 0.5f, 0f * 0.5f), 1.2f), this, ItemType("DimGreenandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimTealandSilver", "ArmorColoredAndSilverTrim", new Vector3(0f * 0.5f, 1f * 0.5f, 0.5f * 0.5f), 1.2f), this, ItemType("DimTealandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimCyanandSilver", "ArmorColoredAndSilverTrim", new Vector3(0f * 0.5f, 1f * 0.5f, 1f * 0.5f), 1.2f), this, ItemType("DimCyanandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimSkyBlueandSilver", "ArmorColoredAndSilverTrim", new Vector3(0.2f * 0.5f, 0.5f * 0.5f, 1f * 0.5f), 1.2f), this, ItemType("DimSkyBlueandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimBlueandSilver", "ArmorColoredAndSilverTrim", new Vector3(0f * 0.5f, 0f * 0.5f, 1f * 0.5f), 1.2f), this, ItemType("DimBlueandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimPurpleandSilver", "ArmorColoredAndSilverTrim", new Vector3(0.5f * 0.5f, 0f * 0.5f, 1f * 0.5f), 1.2f), this, ItemType("DimPurpleandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimVioletandSilver", "ArmorColoredAndSilverTrim", new Vector3(1f * 0.5f, 0f * 0.5f, 1f * 0.5f), 1.2f), this, ItemType("DimVioletandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimPinkandSilver", "ArmorColoredAndSilverTrim", new Vector3(1f * 0.5f, 0.1f * 0.5f, 0.5f * 0.5f), 1.3f), this, ItemType("DimPinkandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimBrownandSilver", "ArmorColoredAndSilverTrim", new Vector3(0.4f * 0.5f, 0.2f * 0.5f, 0f * 0.5f), 1f), this, ItemType("DimBrownandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimBlackandSilver", "ArmorColoredAndSilverTrim", new Vector3(0.6f * 0.5f, 0.6f * 0.5f, 0.6f * 0.5f)), this, ItemType("DimBlackandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimSilverandSilver", "ArmorColoredAndSilverTrim", new Vector3(1f * 0.5f, 1f * 0.5f, 1f * 0.5f), 1.2f), this, ItemType("DimSilverandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("RottenBrownandSilver", "ArmorColoredAndSilverTrim", new Vector3(0.62f, 0.35f, 0.40f)), this, ItemType("RottenBrownandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("RottenGreenandSilver", "ArmorColoredAndSilverTrim", new Vector3(0.58f, 0.63f, 0.13f), 1.2f), this, ItemType("RottenGreenandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("VilePurpleandSilver", "ArmorColoredAndSilverTrim", new Vector3(0.56f, 0.43f, 0.81f), 1.2f), this, ItemType("VilePurpleandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("ShadowPurpleandSilver", "ArmorColoredAndSilverTrim", new Vector3(0.26f, 0.13f, 0.71f), 1.2f), this, ItemType("ShadowPurpleandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("GrossBrownandSilver", "ArmorColoredAndSilverTrim", new Vector3(0.70f, 0.35f, 0.12f)), this, ItemType("GrossBrownandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("GrossPinkandSilver", "ArmorColoredAndSilverTrim", new Vector3(1f, 0.5f, 0.5f), 1.3f), this, ItemType("GrossPinkandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("ViciousRedandSilver", "ArmorColoredAndSilverTrim", new Vector3(0.8f, 0.3f, 0.3f), 1.2f), this, ItemType("ViciousRedandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("FleshRedandSilver", "ArmorColoredAndSilverTrim", new Vector3(0.9f, 0.15f, 0.15f), 1.2f), this, ItemType("FleshRedandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("ShiftingRainbowandSilver", "ArmorColoredAndSilverTrim", 1.2f, 0, 0), this, ItemType("ShiftingRainbowandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("BrightShiftingRainbowandSilver", "ArmorColoredAndSilverTrim", 1.2f, 0, 1), this, ItemType("BrightShiftingRainbowandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("DimShiftingRainbowandSilver", "ArmorColoredAndSilverTrim", 1.2f, 0, 2), this, ItemType("DimShiftingRainbowandSilverDye"));
				//- brightnesscolored -//
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseRed", "ArmorBrightnessColored", new Vector3(1f, 0f, 0f)), this, ItemType("IntenseRedDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseOrange", "ArmorBrightnessColored", new Vector3(1f, 0.5f, 0f)), this, ItemType("IntenseOrangeDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseYellow", "ArmorBrightnessColored", new Vector3(1f, 1f, 0f)), this, ItemType("IntenseYellowDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseLime", "ArmorBrightnessColored", new Vector3(0.5f, 1f, 0f)), this, ItemType("IntenseLimeDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseGreen", "ArmorBrightnessColored", new Vector3(0f, 1f, 0f)), this, ItemType("IntenseGreenDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseTeal", "ArmorBrightnessColored", new Vector3(0f, 1f, 0.5f)), this, ItemType("IntenseTealDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseCyan", "ArmorBrightnessColored", new Vector3(0f, 1f, 1f)), this, ItemType("IntenseCyanDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseSkyBlue", "ArmorBrightnessColored", new Vector3(0.2f, 0.5f, 1f)), this, ItemType("IntenseSkyBlueDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseBlue", "ArmorBrightnessColored", new Vector3(0f, 0f, 1f)), this, ItemType("IntenseBlueDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntensePurple", "ArmorBrightnessColored", new Vector3(0.5f, 0f, 1f)), this, ItemType("IntensePurpleDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseViolet", "ArmorBrightnessColored", new Vector3(1f, 0f, 1f)), this, ItemType("IntenseVioletDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntensePink", "ArmorBrightnessColored", new Vector3(1f, 0.1f, 0.5f)), this, ItemType("IntensePinkDye"));
				//ShaderLoader.AddModArmorShaderData(new DyeHardShader("DummyNumber1", "ArmorColored"), this, ItemType("DummyDyeNumber1"));//used to reset the vanilla dye limit, nothing more.
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseBrown", "ArmorBrightnessColored", new Vector3(0.4f, 0.2f, 0f)), this, ItemType("IntenseBrownDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseBlack", "ArmorBrightnessColored", new Vector3(0.2f, 0.2f, 0.2f)), this, ItemType("IntenseBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseSilver", "ArmorBrightnessColored", new Vector3(2f, 2f, 2f)), this, ItemType("IntenseSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("IntenseShiftingRainbow", "ArmorBrightnessColored", 0, 0), this, ItemType("IntenseShiftingRainbowDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("IntenseBrightShiftingRainbow", "ArmorBrightnessColored", 0, 1), this, ItemType("IntenseBrightShiftingRainbowDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("IntenseDimShiftingRainbow", "ArmorBrightnessColored", 0, 2), this, ItemType("IntenseDimShiftingRainbowDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseRottenBrown", "ArmorBrightnessColored", new Vector3(0.62f, 0.35f, 0.40f)), this, ItemType("IntenseRottenBrownDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseRottenGreen", "ArmorBrightnessColored", new Vector3(0.58f, 0.63f, 0.13f)), this, ItemType("IntenseRottenGreenDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseVilePurple", "ArmorBrightnessColored", new Vector3(0.56f, 0.43f, 0.81f)), this, ItemType("IntenseVilePurpleDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseShadowPurple", "ArmorBrightnessColored", new Vector3(0.26f, 0.13f, 0.71f)), this, ItemType("IntenseShadowPurpleDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseGrossBrown", "ArmorBrightnessColored", new Vector3(0.70f, 0.35f, 0.12f)), this, ItemType("IntenseGrossBrownDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseGrossPink", "ArmorBrightnessColored", new Vector3(1f, 0.5f, 0.5f)), this, ItemType("IntenseGrossPinkDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseViciousRed", "ArmorBrightnessColored", new Vector3(0.8f, 0.3f, 0.3f)), this, ItemType("IntenseViciousRedDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseFleshRed", "ArmorBrightnessColored", new Vector3(0.9f, 0.15f, 0.15f)), this, ItemType("IntenseFleshRedDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("Light", "ArmorBrightnessColored", new Vector3(3f, 3f, 3f)), this, ItemType("LightDye"));
				//- coloredgradient -//
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightYellowGradient", "ArmorColoredGradient", new Vector3(0.5f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), new Vector3(1f * 0.5f + 0.5f, 0.5f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), 1.5f), this, ItemType("BrightYellowGradientDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightCyanGradient", "ArmorColoredGradient", new Vector3(0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0.5f * 0.5f + 0.5f), new Vector3(0f * 0.5f + 0.5f, 0.5f * 0.5f + 0.5f, 1f * 0.5f + 0.5f), 1.5f), this, ItemType("BrightCyanGradientDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightVioletGradient", "ArmorColoredGradient", new Vector3(1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f, 0.5f * 0.5f + 0.5f), new Vector3(0.5f * 0.5f + 0.5f, 0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f), 1.5f), this, ItemType("BrightVioletGradientDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimYellowGradient", "ArmorColoredGradient", new Vector3(0.5f * 0.5f, 1f * 0.5f, 0f * 0.5f), new Vector3(1f * 0.5f, 0.5f * 0.5f, 0f * 0.5f), 1.5f), this, ItemType("DimYellowGradientDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimCyanGradient", "ArmorColoredGradient", new Vector3(0f * 0.5f, 1f * 0.5f, 0.5f * 0.5f), new Vector3(0f * 0.5f, 0.5f * 0.5f, 1f * 0.5f), 1.5f), this, ItemType("DimCyanGradientDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimVioletGradient", "ArmorColoredGradient", new Vector3(1f * 0.5f, 0f * 0.5f, 0.5f * 0.5f), new Vector3(0.5f * 0.5f, 0f * 0.5f, 1f * 0.5f), 1.5f), this, ItemType("DimVioletGradientDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightFlame", "ArmorColoredGradient", new Vector3(1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), new Vector3(1f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), 1.2f), this, ItemType("BrightFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightBlueFlame", "ArmorColoredGradient", new Vector3(0f * 0.5f + 0.5f, 0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f), new Vector3(0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 1f * 0.5f + 0.5f), 1.2f), this, ItemType("BrightBlueFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightGreenFlame", "ArmorColoredGradient", new Vector3(0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), new Vector3(1f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), 1.2f), this, ItemType("BrightGreenFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimFlame", "ArmorColoredGradient", new Vector3(1f * 0.5f, 0f * 0.5f, 0f * 0.5f), new Vector3(1f * 0.5f, 1f * 0.5f, 0f * 0.5f), 1.2f), this, ItemType("DimFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimBlueFlame", "ArmorColoredGradient", new Vector3(0f * 0.5f, 0f * 0.5f, 1f * 0.5f), new Vector3(0f * 0.5f, 1f * 0.5f, 1f * 0.5f), 1.2f), this, ItemType("DimBlueFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimGreenFlame", "ArmorColoredGradient", new Vector3(0f * 0.5f, 1f * 0.5f, 0f * 0.5f), new Vector3(1f * 0.5f, 1f * 0.5f, 0f * 0.5f), 1.2f), this, ItemType("DimGreenFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("ShiftingRainbowFlame", "ArmorColoredGradient", 1.2f, 1, 0), this, ItemType("ShiftingRainbowFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("BrightShiftingRainbowFlame", "ArmorColoredGradient", 1.2f, 1, 1), this, ItemType("BrightShiftingRainbowFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("DimShiftingRainbowFlame", "ArmorColoredGradient", 1.2f, 1, 2), this, ItemType("DimShiftingRainbowFlameDye"));
				//- coloredandblackgradient -//
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("YellowGradientandBlack", "ArmorColoredAndBlackGradient", new Vector3(0.5f, 1f, 0f), new Vector3(1f, 0.5f, 0f), 1.5f), this, ItemType("YellowGradientandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("CyanGradientandBlack", "ArmorColoredAndBlackGradient", new Vector3(0f, 1f, 0.5f), new Vector3(0f, 0.5f, 1f), 1.5f), this, ItemType("CyanGradientandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("VioletGradientandBlack", "ArmorColoredAndBlackGradient", new Vector3(1f, 0f, 0.5f), new Vector3(0.5f, 0f, 1f), 1.5f), this, ItemType("VioletGradientandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightYellowGradientandBlack", "ArmorColoredAndBlackGradient", new Vector3(0.5f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), new Vector3(1f * 0.5f + 0.5f, 0.5f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), 1.5f), this, ItemType("BrightYellowGradientandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightCyanGradientandBlack", "ArmorColoredAndBlackGradient", new Vector3(0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0.5f * 0.5f + 0.5f), new Vector3(0f * 0.5f + 0.5f, 0.5f * 0.5f + 0.5f, 1f * 0.5f + 0.5f), 1.5f), this, ItemType("BrightCyanGradientandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightVioletGradientandBlack", "ArmorColoredAndBlackGradient", new Vector3(1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f, 0.5f * 0.5f + 0.5f), new Vector3(0.5f * 0.5f + 0.5f, 0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f), 1.5f), this, ItemType("BrightVioletGradientandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimYellowGradientandBlack", "ArmorColoredAndBlackGradient", new Vector3(0.5f * 0.5f, 1f * 0.5f, 0f * 0.5f), new Vector3(1f * 0.5f, 0.5f * 0.5f, 0f * 0.5f), 1.5f), this, ItemType("DimYellowGradientandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimCyanGradientandBlack", "ArmorColoredAndBlackGradient", new Vector3(0f * 0.5f, 1f * 0.5f, 0.5f * 0.5f), new Vector3(0f * 0.5f, 0.5f * 0.5f, 1f * 0.5f), 1.5f), this, ItemType("DimCyanGradientandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimVioletGradientandBlack", "ArmorColoredAndBlackGradient", new Vector3(1f * 0.5f, 0f * 0.5f, 0.5f * 0.5f), new Vector3(0.5f * 0.5f, 0f * 0.5f, 1f * 0.5f), 1.5f), this, ItemType("DimVioletGradientandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightFlameandBlack", "ArmorColoredAndBlackGradient", new Vector3(1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), new Vector3(1f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), 1.5f), this, ItemType("BrightFlameandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightBlueFlameandBlack", "ArmorColoredAndBlackGradient", new Vector3(0f * 0.5f + 0.5f, 0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f), new Vector3(0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 1f * 0.5f + 0.5f), 1.5f), this, ItemType("BrightBlueFlameandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightGreenFlameandBlack", "ArmorColoredAndBlackGradient", new Vector3(0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), new Vector3(1f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), 1.5f), this, ItemType("BrightGreenFlameandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimFlameandBlack", "ArmorColoredAndBlackGradient", new Vector3(1f * 0.5f, 0f * 0.5f, 0f * 0.5f), new Vector3(1f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), 1.5f), this, ItemType("DimFlameandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimBlueFlameandBlack", "ArmorColoredAndBlackGradient", new Vector3(0f * 0.5f, 0f * 0.5f, 1f * 0.5f), new Vector3(0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 1f * 0.5f + 0.5f), 1.5f), this, ItemType("DimBlueFlameandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimGreenFlameandBlack", "ArmorColoredAndBlackGradient", new Vector3(0f * 0.5f, 1f * 0.5f, 0f * 0.5f), new Vector3(1f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), 1.5f), this, ItemType("DimGreenFlameandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("ShiftingRainbowFlameandBlack", "ArmorColoredAndBlackGradient", 1.2f, 1, 0), this, ItemType("ShiftingRainbowFlameandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("BrightShiftingRainbowFlameandBlack", "ArmorColoredAndBlackGradient", 1.2f, 1, 1), this, ItemType("BrightShiftingRainbowFlameandBlackDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("DimShiftingRainbowFlameandBlack", "ArmorColoredAndBlackGradient", 1.2f, 1, 2), this, ItemType("DimShiftingRainbowFlameandBlackDye"));
				//- coloredandsilvertrimgradient -//
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("YellowGradientandSilver", "ArmorColoredAndSilverTrimGradient", new Vector3(0.5f, 1f, 0f), new Vector3(1f, 0.5f, 0f), 1.5f), this, ItemType("YellowGradientandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("CyanGradientandSilver", "ArmorColoredAndSilverTrimGradient", new Vector3(0f, 1f, 0.5f), new Vector3(0f, 0.5f, 1f), 1.5f), this, ItemType("CyanGradientandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("VioletGradientandSilver", "ArmorColoredAndSilverTrimGradient", new Vector3(1f, 0f, 0.5f), new Vector3(0.5f, 0f, 1f), 1.5f), this, ItemType("VioletGradientandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightYellowGradientandSilver", "ArmorColoredAndSilverTrimGradient", new Vector3(0.5f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), new Vector3(1f * 0.5f + 0.5f, 0.5f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), 1.5f), this, ItemType("BrightYellowGradientandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightCyanGradientandSilver", "ArmorColoredAndSilverTrimGradient", new Vector3(0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0.5f * 0.5f + 0.5f), new Vector3(0f * 0.5f + 0.5f, 0.5f * 0.5f + 0.5f, 1f * 0.5f + 0.5f), 1.5f), this, ItemType("BrightCyanGradientandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightVioletGradientandSilver", "ArmorColoredAndSilverTrimGradient", new Vector3(1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f, 0.5f * 0.5f + 0.5f), new Vector3(0.5f * 0.5f + 0.5f, 0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f), 1.5f), this, ItemType("BrightVioletGradientandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimYellowGradientandSilver", "ArmorColoredAndSilverTrimGradient", new Vector3(0.5f * 0.5f, 1f * 0.5f, 0f * 0.5f), new Vector3(1f * 0.5f, 0.5f * 0.5f, 0f * 0.5f), 1.5f), this, ItemType("DimYellowGradientandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimCyanGradientandSilver", "ArmorColoredAndSilverTrimGradient", new Vector3(0f * 0.5f, 1f * 0.5f, 0.5f * 0.5f), new Vector3(0f * 0.5f, 0.5f * 0.5f, 1f * 0.5f), 1.5f), this, ItemType("DimCyanGradientandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimVioletGradientandSilver", "ArmorColoredAndSilverTrimGradient", new Vector3(1f * 0.5f, 0f * 0.5f, 0.5f * 0.5f), new Vector3(0.5f * 0.5f, 0f * 0.5f, 1f * 0.5f), 1.5f), this, ItemType("DimVioletGradientandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightFlameandSilver", "ArmorColoredAndSilverTrimGradient", new Vector3(1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), new Vector3(1f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), 1.5f), this, ItemType("BrightFlameandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightBlueFlameandSilver", "ArmorColoredAndSilverTrimGradient", new Vector3(0f * 0.5f + 0.5f, 0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f), new Vector3(0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 1f * 0.5f + 0.5f), 1.5f), this, ItemType("BrightBlueFlameandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrightGreenFlameandSilver", "ArmorColoredAndSilverTrimGradient", new Vector3(0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), new Vector3(1f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), 1.5f), this, ItemType("BrightGreenFlameandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimFlameandSilver", "ArmorColoredAndSilverTrimGradient", new Vector3(1f * 0.5f, 0f * 0.5f, 0f * 0.5f), new Vector3(1f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), 1.5f), this, ItemType("DimFlameandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimBlueFlameandSilver", "ArmorColoredAndSilverTrimGradient", new Vector3(0f * 0.5f, 0f * 0.5f, 1f * 0.5f), new Vector3(0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 1f * 0.5f + 0.5f), 1.5f), this, ItemType("DimBlueFlameandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("DimGreenFlameandSilver", "ArmorColoredAndSilverTrimGradient", new Vector3(0f * 0.5f, 1f * 0.5f, 0f * 0.5f), new Vector3(1f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), 1.5f), this, ItemType("DimGreenFlameandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("ShiftingRainbowFlameandSilver", "ArmorColoredAndSilverTrimGradient", 1.2f, 1, 0), this, ItemType("ShiftingRainbowFlameandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("BrightShiftingRainbowFlameandSilver", "ArmorColoredAndSilverTrimGradient", 1.2f, 1, 1), this, ItemType("BrightShiftingRainbowFlameandSilverDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("DimShiftingRainbowFlameandSilver", "ArmorColoredAndSilverTrimGradient", 1.2f, 1, 2), this, ItemType("DimShiftingRainbowFlameandSilverDye"));
				//- brightnessgradient -//
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseYellowGradient", "ArmorBrightnessGradient", new Vector3(0.5f, 1f, 0f), new Vector3(1f, 0.5f, 0f)), this, ItemType("IntenseYellowGradientDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseCyanGradient", "ArmorBrightnessGradient", new Vector3(0f, 1f, 0.5f), new Vector3(0f, 0.5f, 1f)), this, ItemType("IntenseCyanGradientDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseVioletGradient", "ArmorBrightnessGradient", new Vector3(1f, 0f, 0.5f), new Vector3(0.5f, 0f, 1f)), this, ItemType("IntenseVioletGradientDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseBrightYellowGradient", "ArmorBrightnessGradient", new Vector3(0.5f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), new Vector3(1f * 0.5f + 0.5f, 0.5f * 0.5f + 0.5f, 0f * 0.5f + 0.5f)), this, ItemType("IntenseBrightYellowGradientDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseBrightCyanGradient", "ArmorBrightnessGradient", new Vector3(0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0.5f * 0.5f + 0.5f), new Vector3(0f * 0.5f + 0.5f, 0.5f * 0.5f + 0.5f, 1f * 0.5f + 0.5f)), this, ItemType("IntenseBrightCyanGradientDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseBrightVioletGradient", "ArmorBrightnessGradient", new Vector3(1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f, 0.5f * 0.5f + 0.5f), new Vector3(0.5f * 0.5f + 0.5f, 0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f)), this, ItemType("IntenseBrightVioletGradientDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseDimYellowGradient", "ArmorBrightnessGradient", new Vector3(0.5f * 0.5f, 1f * 0.5f, 0f * 0.5f), new Vector3(1f * 0.5f, 0.5f * 0.5f, 0f * 0.5f)), this, ItemType("IntenseDimYellowGradientDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseDimCyanGradient", "ArmorBrightnessGradient", new Vector3(0f * 0.5f, 1f * 0.5f, 0.5f * 0.5f), new Vector3(0f * 0.5f, 0.5f * 0.5f, 1f * 0.5f)), this, ItemType("IntenseDimCyanGradientDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseDimVioletGradient", "ArmorBrightnessGradient", new Vector3(1f * 0.5f, 0f * 0.5f, 0.5f * 0.5f), new Vector3(0.5f * 0.5f, 0f * 0.5f, 1f * 0.5f)), this, ItemType("IntenseDimVioletGradientDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseBrightFlame", "ArmorBrightnessGradient", new Vector3(1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), new Vector3(1f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f)), this, ItemType("IntenseBrightFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseBrightBlueFlame", "ArmorBrightnessGradient", new Vector3(0f * 0.5f + 0.5f, 0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f), new Vector3(0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 1f * 0.5f + 0.5f)), this, ItemType("IntenseBrightBlueFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseBrightGreenFlame", "ArmorBrightnessGradient", new Vector3(0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f), new Vector3(1f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f)), this, ItemType("IntenseBrightGreenFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseDimFlame", "ArmorBrightnessGradient", new Vector3(1f * 0.5f, 0f * 0.5f, 0f * 0.5f), new Vector3(1f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f)), this, ItemType("IntenseDimFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseDimBlueFlame", "ArmorBrightnessGradient", new Vector3(0f * 0.5f, 0f * 0.5f, 1f * 0.5f), new Vector3(0f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 1f * 0.5f + 0.5f)), this, ItemType("IntenseDimBlueFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("IntenseDimGreenFlame", "ArmorBrightnessGradient", new Vector3(0f * 0.5f, 1f * 0.5f, 0f * 0.5f), new Vector3(1f * 0.5f + 0.5f, 1f * 0.5f + 0.5f, 0f * 0.5f + 0.5f)), this, ItemType("IntenseDimGreenFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("IntenseShiftingRainbowFlame", "ArmorBrightnessGradient", 1.2f, 1, 0), this, ItemType("IntenseShiftingRainbowFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("IntenseBrightShiftingRainbowFlame", "ArmorBrightnessGradient", 1.2f, 1, 1), this, ItemType("IntenseBrightShiftingRainbowFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("IntenseDimShiftingRainbowFlame", "ArmorBrightnessGradient", 1.2f, 1, 2), this, ItemType("IntenseDimShiftingRainbowFlameDye"));
				//- livingflame -//
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BlueLivingFlame", "ArmorLivingFlame", new Vector3(0f, 0.9f, 1f), new Vector3(0f, 0.2f, 1f)), this, ItemType("BlueLivingFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("GreenLivingFlame", "ArmorLivingFlame", new Vector3(1.1f, 1.2f, 0f), new Vector3(0.2f, 1f, 0f)), this, ItemType("GreenLivingFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("YellowLivingGradient", "ArmorLivingFlame", new Vector3(0.2f, 1f, 0f), new Vector3(0.9f, 0.5f, 0f)), this, ItemType("YellowLivingGradientDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("CyanLivingGradient", "ArmorLivingFlame", new Vector3(0f, 1f, 0.2f), new Vector3(0f, 0.5f, 0.9f)), this, ItemType("CyanLivingGradientDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("VioletLivingGradient", "ArmorLivingFlame", new Vector3(1f, 0f, 0.2f), new Vector3(0.5f, 0f, 0.9f)), this, ItemType("VioletLivingGradientDye"));
				//- wisp -//
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("Spirit", "ArmorWisp", new Vector3(0.76f, 0.96f, 1f), new Vector3(0.13f, 0.78f, 0.99f)), this, ItemType("SpiritDye"));
				//- highcontrastglow -//
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("RedHighlight", "ArmorHighContrastGlow", new Vector3(1f, 0f, 0f)), this, ItemType("RedHighlightDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("OrangeHighlight", "ArmorHighContrastGlow", new Vector3(1f, 0.5f, 0f)), this, ItemType("OrangeHighlightDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("YellowHighlight", "ArmorHighContrastGlow", new Vector3(1f, 1f, 0f)), this, ItemType("YellowHighlightDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("LimeHighlight", "ArmorHighContrastGlow", new Vector3(0.5f, 1f, 0f)), this, ItemType("LimeHighlightDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("TealHighlight", "ArmorHighContrastGlow", new Vector3(0f, 1f, 0.5f)), this, ItemType("TealHighlightDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("CyanHighlight", "ArmorHighContrastGlow", new Vector3(0f, 1f, 1f)), this, ItemType("CyanHighlightDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("SkyBlueHighlight", "ArmorHighContrastGlow", new Vector3(0.2f, 0.5f, 1f)), this, ItemType("SkyBlueHighlightDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BlueHighlight", "ArmorHighContrastGlow", new Vector3(0f, 0f, 1f)), this, ItemType("BlueHighlightDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("PurpleHighlight", "ArmorHighContrastGlow", new Vector3(0.5f, 0f, 1f)), this, ItemType("PurpleHighlightDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("VioletHighlight", "ArmorHighContrastGlow", new Vector3(1f, 0f, 1f)), this, ItemType("VioletHighlightDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("PinkHighlight", "ArmorHighContrastGlow", new Vector3(1f, 0.1f, 0.5f)), this, ItemType("PinkHighlightDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrownHighlight", "ArmorHighContrastGlow", new Vector3(0.4f, 0.2f, 0f)), this, ItemType("BrownHighlightDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BlackHighlight", "ArmorHighContrastGlow", new Vector3(0.6f, 0.6f, 0.6f)), this, ItemType("BlackHighlightDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("SilverHighlight", "ArmorHighContrastGlow", new Vector3(1f, 1f, 1f), 1f), this, ItemType("SilverHighlightDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("ShiftingRainbowHighlight", "ArmorHighContrastGlow", 0, 0), this, ItemType("ShiftingRainbowHighlightDye"));
				//- reflectivecolor -//
				ShaderLoader.AddModArmorShaderData(new DyeHardReflectiveShader("ReflectiveTin", "ArmorReflectiveColor", new Vector3(1.13f, 1.05f, 0.89f), false), this, ItemType("ReflectiveTinDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardReflectiveShader("ReflectiveTungsten", "ArmorReflectiveColor", new Vector3(1f, 1.14f, 1f), false), this, ItemType("ReflectiveTungstenDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardReflectiveShader("ReflectivePlatinum", "ArmorReflectiveColor", new Vector3(1.1f, 1.2f, 1.3f), false), this, ItemType("ReflectivePlatinumDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardReflectiveShader("ReflectiveDemonite", "ArmorReflectiveColor", new Vector3(1f, 0.9f, 1.2f), false), this, ItemType("ReflectiveDemoniteDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardReflectiveShader("ReflectiveCobalt", "ArmorReflectiveColor", new Vector3(0.45f, 0.8f, 1.1f), false), this, ItemType("ReflectiveCobaltDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardReflectiveShader("ReflectiveMythril", "ArmorReflectiveColor", new Vector3(0.64f, 1.13f, 1f), false), this, ItemType("ReflectiveMythrilDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardReflectiveShader("ReflectiveAdamantite", "ArmorReflectiveColor", new Vector3(1.05f, 0.3f, 0.55f), false), this, ItemType("ReflectiveAdamantiteDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardReflectiveShader("ReflectiveShiftingRainbow", "ArmorReflectiveColor", true), this, ItemType("ReflectiveShiftingRainbowDye"));
				//- hades -//
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("RedHades", "ArmorHades", new Vector3(1.5f, 0.5f, 0.5f), new Vector3(1.5f, 0.5f, 0.5f)), this, ItemType("RedHadesDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("OrangeHades", "ArmorHades", new Vector3(1.5f, 0.75f, 0.5f), new Vector3(1.5f, 0.75f, 0.5f)), this, ItemType("OrangeHadesDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("YellowHades", "ArmorHades", new Vector3(1.5f, 1.5f, 0.5f), new Vector3(1.5f, 1.5f, 0.5f)), this, ItemType("YellowHadesDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("LimeHades", "ArmorHades", new Vector3(0.75f, 1.5f, 0.5f), new Vector3(0.75f, 1.5f, 0.5f)), this, ItemType("LimeHadesDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("GreenHades", "ArmorHades", new Vector3(0.5f, 1.5f, 0.5f), new Vector3(0.5f, 1.5f, 0.5f)), this, ItemType("GreenHadesDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("TealHades", "ArmorHades", new Vector3(0.5f, 1.5f, 0.75f), new Vector3(0.5f, 1.5f, 0.75f)), this, ItemType("TealHadesDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("CyanHades", "ArmorHades", new Vector3(0.5f, 1.5f, 1.5f), new Vector3(0.5f, 1.5f, 1.5f)), this, ItemType("CyanHadesDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("SkyBlueHades", "ArmorHades", new Vector3(0.7f, 0.75f, 1.5f), new Vector3(0.7f, 0.75f, 1.5f)), this, ItemType("SkyBlueHadesDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BlueHades", "ArmorHades", new Vector3(0.5f, 0.5f, 1.5f), new Vector3(0.5f, 0.5f, 1.5f)), this, ItemType("BlueHadesDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("PurpleHades", "ArmorHades", new Vector3(0.75f, 0.5f, 1.5f), new Vector3(0.75f, 0.5f, 1.5f)), this, ItemType("PurpleHadesDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("VioletHades", "ArmorHades", new Vector3(1.5f, 0.5f, 1.5f), new Vector3(1.5f, 0.5f, 1.5f)), this, ItemType("VioletHadesDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("PinkHades", "ArmorHades", new Vector3(1.5f, 0.6f, 1f), new Vector3(1.5f, 0.6f, 1f)), this, ItemType("PinkHadesDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrownHades", "ArmorHades", new Vector3(0.9f, 0.7f, 0.5f), new Vector3(0.9f, 0.7f, 0.5f)), this, ItemType("BrownHadesDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BlackHades", "ArmorHades", new Vector3(0.4f, 0.4f, 0.4f), new Vector3(0.4f, 0.4f, 0.4f)), this, ItemType("BlackHadesDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("SilverHades", "ArmorHades", new Vector3(1.5f, 1.5f, 1.5f), new Vector3(1.5f, 1.5f, 1.5f)), this, ItemType("SilverHadesDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("ShiftingRainbowHades", "ArmorHades", 0, 0), this, ItemType("ShiftingRainbowHadesDye"));
				//- twilight -//
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("RedTwilight", "ArmorTwilight", new Vector3(1f, 0.1f, 0.1f)), this, ItemType("RedTwilightDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("OrangeTwilight", "ArmorTwilight", new Vector3(1f, 0.5f, 0.1f)), this, ItemType("OrangeTwilightDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("YellowTwilight", "ArmorTwilight", new Vector3(1f, 1f, 0.1f)), this, ItemType("YellowTwilightDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("LimeTwilight", "ArmorTwilight", new Vector3(0.5f, 1f, 0.1f)), this, ItemType("LimeTwilightDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("GreenTwilight", "ArmorTwilight", new Vector3(0.1f, 1f, 0.1f)), this, ItemType("GreenTwilightDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("TealTwilight", "ArmorTwilight", new Vector3(0.1f, 1f, 0.5f)), this, ItemType("TealTwilightDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("CyanTwilight", "ArmorTwilight", new Vector3(0.1f, 1f, 1f)), this, ItemType("CyanTwilightDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("SkyBlueTwilight", "ArmorTwilight", new Vector3(0.2f, 0.5f, 1f)), this, ItemType("SkyBlueTwilightDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BlueTwilight", "ArmorTwilight", new Vector3(0.1f, 0.1f, 1f)), this, ItemType("BlueTwilightDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("VioletTwilight", "ArmorTwilight", new Vector3(1f, 0.1f, 1f)), this, ItemType("VioletTwilightDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("PinkTwilight", "ArmorTwilight", new Vector3(1f, 0.2f, 0.5f)), this, ItemType("PinkTwilightDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrownTwilight", "ArmorTwilight", new Vector3(0.4f, 0.2f, 0.1f)), this, ItemType("BrownTwilightDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BlackTwilight", "ArmorTwilight", new Vector3(0.6f, 0.6f, 0.6f)), this, ItemType("BlackTwilightDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("SilverTwilight", "ArmorTwilight", new Vector3(1f, 1f, 1f)), this, ItemType("SilverTwilightDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("ShiftingRainbowTwilight", "ArmorTwilight", 0, 0), this, ItemType("ShiftingRainbowTwilightDye"));
				//- acid -//
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("PureRedAcid", "ArmorAcid", new Vector3(1.5f, 0f, 0f)), this, ItemType("PureRedAcidDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("OrangeAcid", "ArmorAcid", new Vector3(1.5f, 0.7f, 0f)), this, ItemType("OrangeAcidDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("YellowAcid", "ArmorAcid", new Vector3(1.5f, 1.5f, 0f)), this, ItemType("YellowAcidDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("LimeAcid", "ArmorAcid", new Vector3(0.7f, 1.5f, 0f)), this, ItemType("LimeAcidDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("PureGreenAcid", "ArmorAcid", new Vector3(0f, 1.5f, 0f)), this, ItemType("PureGreenAcidDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("TealAcid", "ArmorAcid", new Vector3(0f, 1.5f, 0.7f)), this, ItemType("TealAcidDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("CyanAcid", "ArmorAcid", new Vector3(0f, 1.5f, 1.5f)), this, ItemType("CyanAcidDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("SkyBlueAcid", "ArmorAcid", new Vector3(0.4f, 0.7f, 1.5f)), this, ItemType("SkyBlueAcidDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("PureBlueAcid", "ArmorAcid", new Vector3(0f, 0f, 1.5f)), this, ItemType("PureBlueAcidDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("PurpleAcid", "ArmorAcid", new Vector3(0.7f, 0f, 1.5f)), this, ItemType("PurpleAcidDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("VioletAcid", "ArmorAcid", new Vector3(1.5f, 0f, 1.5f)), this, ItemType("VioletAcidDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("PinkAcid", "ArmorAcid", new Vector3(1.5f, 0.3f, 0.7f)), this, ItemType("PinkAcidDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrownAcid", "ArmorAcid", new Vector3(0.7f, 0.5f, 0.3f)), this, ItemType("BrownAcidDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BlackAcid", "ArmorAcid", new Vector3(0.6f, 0.6f, 0.6f)), this, ItemType("BlackAcidDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("SilverAcid", "ArmorAcid", new Vector3(1f, 1f, 1f)), this, ItemType("SilverAcidDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("ShiftingRainbowAcid", "ArmorAcid", 0, 0), this, ItemType("ShiftingRainbowAcidDye"));
				//- mushroom(midtone) -//
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("RedMidtone", "ArmorMushroom", new Vector3(1f, 0f, 0f)), this, ItemType("RedMidtoneDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("OrangeMidtone", "ArmorMushroom", new Vector3(1f, 0.5f, 0f)), this, ItemType("OrangeMidtoneDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("YellowMidtone", "ArmorMushroom", new Vector3(1f, 1f, 0f)), this, ItemType("YellowMidtoneDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("LimeMidtone", "ArmorMushroom", new Vector3(0.5f, 1f, 0f)), this, ItemType("LimeMidtoneDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("GreenMidtone", "ArmorMushroom", new Vector3(0f, 1f, 0f)), this, ItemType("GreenMidtoneDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("TealMidtone", "ArmorMushroom", new Vector3(0f, 1f, 0.5f)), this, ItemType("TealMidtoneDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("CyanMidtone", "ArmorMushroom", new Vector3(0f, 1f, 1f)), this, ItemType("CyanMidtoneDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("SkyBlueMidtone", "ArmorMushroom", new Vector3(0.2f, 0.5f, 1f)), this, ItemType("SkyBlueMidtoneDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BlueMidtone", "ArmorMushroom", new Vector3(0f, 0f, 1f)), this, ItemType("BlueMidtoneDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("PurpleMidtone", "ArmorMushroom", new Vector3(0.5f, 0f, 1f)), this, ItemType("PurpleMidtoneDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("VioletMidtone", "ArmorMushroom", new Vector3(1f, 0f, 1f)), this, ItemType("VioletMidtoneDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("PinkMidtone", "ArmorMushroom", new Vector3(1f, 0.1f, 0.5f)), this, ItemType("PinkMidtoneDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrownMidtone", "ArmorMushroom", new Vector3(0.4f, 0.2f, 0f)), this, ItemType("BrownMidtoneDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BlackMidtone", "ArmorMushroom", new Vector3(0.6f, 0.6f, 0.6f)), this, ItemType("BlackMidtoneDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("SilverMidtone", "ArmorMushroom", new Vector3(1f, 1f, 1f)), this, ItemType("SilverMidtoneDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("ShiftingRainbowMidtone", "ArmorMushroom", 0, 0), this, ItemType("ShiftingRainbowMidtoneDye"));
				//- phase -//
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("RedPhase", "ArmorPhase", new Vector3(1.3f, 0.2f, 0.2f)), this, ItemType("RedPhaseDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("OrangePhase", "ArmorPhase", new Vector3(1.1f, 0.45f, 0.2f)), this, ItemType("OrangePhaseDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("YellowPhase", "ArmorPhase", new Vector3(0.9f, 0.9f, 0.2f)), this, ItemType("YellowPhaseDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("LimePhase", "ArmorPhase", new Vector3(0.45f, 0.9f, 0.2f)), this, ItemType("LimePhaseDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("GreenPhase", "ArmorPhase", new Vector3(0.2f, 0.9f, 0.2f)), this, ItemType("GreenPhaseDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("TealPhase", "ArmorPhase", new Vector3(0.2f, 0.95f, 0.45f)), this, ItemType("TealPhaseDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("CyanPhase", "ArmorPhase", new Vector3(0.2f, 0.95f, 0.95f)), this, ItemType("CyanPhaseDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("SkyBluePhase", "ArmorPhase", new Vector3(0.22f, 0.4f, 1.5f)), this, ItemType("SkyBluePhaseDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BluePhase", "ArmorPhase", new Vector3(0.2f, 0.2f, 1.5f)), this, ItemType("BluePhaseDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("VioletPhase", "ArmorPhase", new Vector3(1.45f, 0.2f, 1.45f)), this, ItemType("VioletPhaseDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("PinkPhase", "ArmorPhase", new Vector3(1.3f, 0.3f, 0.7f)), this, ItemType("PinkPhaseDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrownPhase", "ArmorPhase", new Vector3(0.6f, 0.4f, 0.2f)), this, ItemType("BrownPhaseDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BlackPhase", "ArmorPhase", new Vector3(0.2f, 0.2f, 0.2f)), this, ItemType("BlackPhaseDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("SilverPhase", "ArmorPhase", new Vector3(0.65f, 0.65f, 0.65f)), this, ItemType("SilverPhaseDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("ShiftingRainbowPhase", "ArmorPhase", 0, 0), this, ItemType("ShiftingRainbowPhaseDye"));
				//- nebula -//
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("RedNebula", "ArmorNebula", new Vector3(1f, 0f, 0f), new Vector3(1f, 1f, 1f)), this, ItemType("RedNebulaDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("OrangeNebula", "ArmorNebula", new Vector3(1f, 0.5f, 0f), new Vector3(1f, 1f, 1f)), this, ItemType("OrangeNebulaDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("YellowNebula", "ArmorNebula", new Vector3(1f, 1f, 0f), new Vector3(1f, 1f, 1f)), this, ItemType("YellowNebulaDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("LimeNebula", "ArmorNebula", new Vector3(0.5f, 1f, 0f), new Vector3(1f, 1f, 1f)), this, ItemType("LimeNebulaDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("GreenNebula", "ArmorNebula", new Vector3(0f, 1f, 0f), new Vector3(1f, 1f, 1f)), this, ItemType("GreenNebulaDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("TealNebula", "ArmorNebula", new Vector3(0f, 1f, 0.5f), new Vector3(1f, 1f, 1f)), this, ItemType("TealNebulaDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("CyanNebula", "ArmorNebula", new Vector3(0f, 1f, 1f), new Vector3(1f, 1f, 1f)), this, ItemType("CyanNebulaDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("SkyBlueNebula", "ArmorNebula", new Vector3(0.2f, 0.5f, 1f), new Vector3(1f, 1f, 1f)), this, ItemType("SkyBlueNebulaDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BlueNebula", "ArmorNebula", new Vector3(0f, 0f, 1f), new Vector3(1f, 1f, 1f)), this, ItemType("BlueNebulaDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("PurpleNebula", "ArmorNebula", new Vector3(0.5f, 0f, 1f), new Vector3(1f, 1f, 1f)), this, ItemType("PurpleNebulaDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("PinkNebula", "ArmorNebula", new Vector3(1f, 0.1f, 0.5f), new Vector3(1f, 1f, 1f)), this, ItemType("PinkNebulaDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrownNebula", "ArmorNebula", new Vector3(0.4f, 0.2f, 0f), new Vector3(1f, 1f, 1f)), this, ItemType("BrownNebulaDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BlackNebula", "ArmorNebula", new Vector3(0.6f, 0.6f, 0.6f), new Vector3(1f, 1f, 1f)), this, ItemType("BlackNebulaDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("SilverNebula", "ArmorNebula", new Vector3(1f, 1f, 1f), new Vector3(0.6f, 0.6f, 0.6f)), this, ItemType("SilverNebulaDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("ShiftingRainbowNebula", "ArmorNebula", new Vector3(1f, 1f, 1f), 0, 0), this, ItemType("ShiftingRainbowNebulaDye"));
				//- vortex -//
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("RedVortex", "ArmorVortex", new Vector3(0.5f, 0.1f, 0.1f), new Vector3(1f, 1f, 1f)), this, ItemType("RedVortexDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("OrangeVortex", "ArmorVortex", new Vector3(0.5f, 0.35f, 0.1f), new Vector3(1f, 1f, 1f)), this, ItemType("OrangeVortexDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("YellowVortex", "ArmorVortex", new Vector3(0.5f, 0.5f, 0.1f), new Vector3(1f, 1f, 1f)), this, ItemType("YellowVortexDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("LimeVortex", "ArmorVortex", new Vector3(0.35f, 0.5f, 0.1f), new Vector3(1f, 1f, 1f)), this, ItemType("LimeVortexDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("GreenVortex", "ArmorVortex", new Vector3(0.1f, 0.5f, 0.1f), new Vector3(1f, 1f, 1f)), this, ItemType("GreenVortexDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("CyanVortex", "ArmorVortex", new Vector3(0.1f, 0.5f, 0.5f), new Vector3(1f, 1f, 1f)), this, ItemType("CyanVortexDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("SkyBlueVortex", "ArmorVortex", new Vector3(0.1f, 0.35f, 0.5f), new Vector3(1f, 1f, 1f)), this, ItemType("SkyBlueVortexDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BlueVortex", "ArmorVortex", new Vector3(0.1f, 0.1f, 0.5f), new Vector3(1f, 1f, 1f)), this, ItemType("BlueVortexDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("PurpleVortex", "ArmorVortex", new Vector3(0.35f, 0.1f, 0.5f), new Vector3(1f, 1f, 1f)), this, ItemType("PurpleVortexDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("VioletVortex", "ArmorVortex", new Vector3(0.5f, 0.1f, 0.5f), new Vector3(1f, 1f, 1f)), this, ItemType("VioletVortexDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("PinkVortex", "ArmorVortex", new Vector3(0.5f, 0.1f, 0.35f), new Vector3(1f, 1f, 1f)), this, ItemType("PinkVortexDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrownVortex", "ArmorVortex", new Vector3(0.2f, 0.1f, 0.1f), new Vector3(1f, 1f, 1f)), this, ItemType("BrownVortexDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BlackVortex", "ArmorVortex", new Vector3(0.4f, 0.4f, 0.4f), new Vector3(1f, 1f, 1f)), this, ItemType("BlackVortexDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("SilverVortex", "ArmorVortex", new Vector3(0.7f, 0.7f, 0.7f), new Vector3(1f, 1f, 1f)), this, ItemType("SilverVortexDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("ShiftingRainbowVortex", "ArmorVortex", new Vector3(1f, 1f, 1f), 0, 0), this, ItemType("ShiftingRainbowVortexDye"));
				//- stardust -//
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("RedStardust", "ArmorStardust", new Vector3(1f, 0.2f, 0.2f), new Vector3(1f, 1f, 1f)), this, ItemType("RedStardustDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("OrangeStardust", "ArmorStardust", new Vector3(1f, 0.6f, 0.2f), new Vector3(1f, 1f, 1f)), this, ItemType("OrangeStardustDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("YellowStardust", "ArmorStardust", new Vector3(1f, 1f, 0.2f), new Vector3(1f, 1f, 1f)), this, ItemType("YellowStardustDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("LimeStardust", "ArmorStardust", new Vector3(0.6f, 1f, 0.2f), new Vector3(1f, 1f, 1f)), this, ItemType("LimeStardustDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("GreenStardust", "ArmorStardust", new Vector3(0.2f, 1f, 0.2f), new Vector3(1f, 1f, 1f)), this, ItemType("GreenStardustDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("TealStardust", "ArmorStardust", new Vector3(0.2f, 1f, 0.6f), new Vector3(1f, 1f, 1f)), this, ItemType("TealStardustDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("CyanStardust", "ArmorStardust", new Vector3(0.2f, 1f, 1f), new Vector3(1f, 1f, 1f)), this, ItemType("CyanStardustDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BlueStardust", "ArmorStardust", new Vector3(0.2f, 0.2f, 1f), new Vector3(1f, 1f, 1f)), this, ItemType("BlueStardustDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("PurpleStardust", "ArmorStardust", new Vector3(0.6f, 0.2f, 1f), new Vector3(1f, 1f, 1f)), this, ItemType("PurpleStardustDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("VioletStardust", "ArmorStardust", new Vector3(1f, 0.2f, 1f), new Vector3(1f, 1f, 1f)), this, ItemType("VioletStardustDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("PinkStardust", "ArmorStardust", new Vector3(1f, 0.3f, 0.6f), new Vector3(1f, 1f, 1f)), this, ItemType("PinkStardustDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrownStardust", "ArmorStardust", new Vector3(0.5f, 0.4f, 0.2f), new Vector3(1f, 1f, 1f)), this, ItemType("BrownStardustDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BlackStardust", "ArmorStardust", new Vector3(0.3f, 0.3f, 0.3f), new Vector3(0.6f, 0.6f, 0.6f)), this, ItemType("BlackStardustDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("SilverStardust", "ArmorStardust", new Vector3(0.5f, 0.5f, 0.5f), new Vector3(1f, 1f, 1f)), this, ItemType("SilverStardustDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("ShiftingRainbowStardust", "ArmorStardust", new Vector3(1f, 1f, 1f), 0, 0), this, ItemType("ShiftingRainbowStardustDye"));
				//- gel -//
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("RedGel", "ArmorGel", new Vector3(1.4f, 0.2f, 0.2f), new Vector3(0.1f, 0f, 0f)), this, ItemType("RedGelDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("OrangeGel", "ArmorGel", new Vector3(1.4f, 0.7f, 0.2f), new Vector3(0.1f, 0.05f, 0f)), this, ItemType("OrangeGelDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("YellowGel", "ArmorGel", new Vector3(1.4f, 1.4f, 0.2f), new Vector3(0.1f, 0.1f, 0f)), this, ItemType("YellowGelDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("LimeGel", "ArmorGel", new Vector3(0.7f, 1.4f, 0.2f), new Vector3(0.05f, 0.1f, 0f)), this, ItemType("LimeGelDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("GreenGel", "ArmorGel", new Vector3(0.2f, 1.4f, 0.2f), new Vector3(0f, 0.1f, 0f)), this, ItemType("GreenGelDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("TealGel", "ArmorGel", new Vector3(0.2f, 1.4f, 0.7f), new Vector3(0f, 0.1f, 0.05f)), this, ItemType("TealGelDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("CyanGel", "ArmorGel", new Vector3(0.2f, 1.4f, 1.4f), new Vector3(0f, 0.1f, 0.1f)), this, ItemType("CyanGelDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BlueGel", "ArmorGel", new Vector3(0.2f, 0.2f, 1.4f), new Vector3(0f, 0f, 0.1f)), this, ItemType("BlueGelDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("PurpleGel", "ArmorGel", new Vector3(0.7f, 0.2f, 1.4f), new Vector3(0f, 0f, 0.1f)), this, ItemType("PurpleGelDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("VioletGel", "ArmorGel", new Vector3(1.4f, 0.2f, 1.4f), new Vector3(0.1f, 0f, 0.1f)), this, ItemType("VioletGelDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("PinkGel", "ArmorGel", new Vector3(1.4f, 0.3f, 0.7f), new Vector3(0.1f, 0.01f, 0.05f)), this, ItemType("PinkGelDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrownGel", "ArmorGel", new Vector3(0.55f, 0.3f, 0.2f), new Vector3(0.055f, 0.03f, 0f)), this, ItemType("BrownGelDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BlackGel", "ArmorGel", new Vector3(0.6f, 0.6f, 0.6f), new Vector3(0.1f, 0.1f, 0.1f)), this, ItemType("BlackGelDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("SilverGel", "ArmorGel", new Vector3(1.4f, 1.4f, 1.4f), new Vector3(0.1f, 0.1f, 0.1f)), this, ItemType("SilverGelDye"));
				//- Skiphs's Blood(gods' blood) -//
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("RedGodsBlood", "ArmorGel", new Vector3(0f, -1f, -1f), new Vector3(2.2f, 1f, 1f)), this, ItemType("RedGodsBlood"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("OrangeGodsBlood", "ArmorGel", new Vector3(0f, -0.5f, -1f), new Vector3(2.2f, 1.5f, 1f)), this, ItemType("OrangeGodsBlood"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("YellowGodsBlood", "ArmorGel", new Vector3(0f, 0f, -1f), new Vector3(2.2f, 2.2f, 1f)), this, ItemType("YellowGodsBlood"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("LimeGodsBlood", "ArmorGel", new Vector3(-0.5f, 0f, -1f), new Vector3(1.5f, 2.2f, 1f)), this, ItemType("LimeGodsBlood"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("GreenGodsBlood", "ArmorGel", new Vector3(-1f, 0f, -1f), new Vector3(1f, 2.2f, 1f)), this, ItemType("GreenGodsBlood"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("TealGodsBlood", "ArmorGel", new Vector3(-1f, 0f, -0.5f), new Vector3(1f, 2.2f, 1.5f)), this, ItemType("TealGodsBlood"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("CyanGodsBlood", "ArmorGel", new Vector3(-1f, 0f, 0f), new Vector3(1f, 2.2f, 2.2f)), this, ItemType("CyanGodsBlood"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("SkyBlueGodsBlood", "ArmorGel", new Vector3(-1f, -0.5f, -0.2f), new Vector3(1.2f, 1.5f, 2.2f)), this, ItemType("SkyBlueGodsBlood"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BlueGodsBlood", "ArmorGel", new Vector3(-1f, -1f, 0f), new Vector3(1f, 1f, 2.2f)), this, ItemType("BlueGodsBlood"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("VioletGodsBlood", "ArmorGel", new Vector3(0f, -1f, 0f), new Vector3(2.2f, 1f, 2.2f)), this, ItemType("VioletGodsBlood"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("PinkGodsBlood", "ArmorGel", new Vector3(-0.1f, -1f, -0.5f), new Vector3(2.2f, 1.1f, 1.5f)), this, ItemType("PinkGodsBlood"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrownGodsBlood", "ArmorGel", new Vector3(0f, -0.3f, -0.5f), new Vector3(1.4f, 1.2f, 1f)), this, ItemType("BrownGodsBlood"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BlackGodsBlood", "ArmorGel", new Vector3(-1f, -1f, -1f), new Vector3(1.6f, 1.6f, 1.6f)), this, ItemType("BlackGodsBlood"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("SilverGodsBlood", "ArmorGel", new Vector3(-0.6f, -0.6f, -0.6f), new Vector3(2.2f, 2.2f, 2.2f)), this, ItemType("SilverGodsBlood"));
				//- flow(Ooze) -//
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("RedOoze", "ArmorFlow", new Vector3(0.9f, 0.6f, 0.6f), new Vector3(1f, 0.1f, 0.1f)), this, ItemType("RedOozeDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("OrangeOoze", "ArmorFlow", new Vector3(1f, 0.9f, 0.6f), new Vector3(1f, 0.5f, 0.1f)), this, ItemType("OrangeOozeDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("YellowOoze", "ArmorFlow", new Vector3(1f, 1f, 0.6f), new Vector3(1f, 1f, 0.1f)), this, ItemType("YellowOozeDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("LimeOoze", "ArmorFlow", new Vector3(0.9f, 1f, 0.6f), new Vector3(0.5f, 1f, 0.1f)), this, ItemType("LimeOozeDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("GreenOoze", "ArmorFlow", new Vector3(0.6f, 0.9f, 0.6f), new Vector3(0.1f, 1f, 0.1f)), this, ItemType("GreenOozeDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("TealOoze", "ArmorFlow", new Vector3(0.8f, 1f, 0.9f), new Vector3(0.1f, 1f, 0.6f)), this, ItemType("TealOozeDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("CyanOoze", "ArmorFlow", new Vector3(0.8f, 1f, 1f), new Vector3(0.1f, 1f, 1f)), this, ItemType("CyanOozeDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("SkyBlueOoze", "ArmorFlow", new Vector3(0.6f, 0.9f, 1f), new Vector3(0.3f, 0.6f, 1f)), this, ItemType("SkyBlueOozeDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BlueOoze", "ArmorFlow", new Vector3(0.6f, 0.6f, 0.9f), new Vector3(0.1f, 0.1f, 1f)), this, ItemType("BlueOozeDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("VioletOoze", "ArmorFlow", new Vector3(1f, 0.6f, 0.9f), new Vector3(1f, 0.1f, 1f)), this, ItemType("VioletOozeDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("PinkOoze", "ArmorFlow", new Vector3(1f, 0.5f, 0.9f), new Vector3(1f, 0.2f, 0.6f)), this, ItemType("PinkOozeDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrownOoze", "ArmorFlow", new Vector3(0.8f, 0.6f, 0.5f), new Vector3(0.5f, 0.3f, 0.1f)), this, ItemType("BrownOozeDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BlackOoze", "ArmorFlow", new Vector3(0.9f, 0.9f, 0.9f), new Vector3(0.5f, 0.5f, 0.5f)), this, ItemType("BlackOozeDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("SilverOoze", "ArmorFlow", new Vector3(1f, 1f, 1f), new Vector3(0.7f, 0.7f, 0.7f)), this, ItemType("SilverOozeDye"));
				//- forcefield(unused) -//
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("RedForceField", "ArmorForceField", new Vector3(1f, 0f, 0f)), this, ItemType("RedForceFieldDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("OrangeForceField", "ArmorForceField", new Vector3(1f, 0.5f, 0f)), this, ItemType("OrangeForceFieldDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("YellowForceField", "ArmorForceField", new Vector3(1f, 1f, 0f)), this, ItemType("YellowForceFieldDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("LimeForceField", "ArmorForceField", new Vector3(0.5f, 1f, 0f)), this, ItemType("LimeForceFieldDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("GreenForceField", "ArmorForceField", new Vector3(0f, 1f, 0f)), this, ItemType("GreenForceFieldDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("TealForceField", "ArmorForceField", new Vector3(0f, 1f, 0.5f)), this, ItemType("TealForceFieldDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("CyanForceField", "ArmorForceField", new Vector3(0f, 1f, 1f)), this, ItemType("CyanForceFieldDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("SkyBlueForceField", "ArmorForceField", new Vector3(0.2f, 0.5f, 1f)), this, ItemType("SkyBlueForceFieldDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BlueForceField", "ArmorForceField", new Vector3(0f, 0f, 1f)), this, ItemType("BlueForceFieldDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("PurpleForceField", "ArmorForceField", new Vector3(0.5f, 0f, 1f)), this, ItemType("PurpleForceFieldDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("VioletForceField", "ArmorForceField", new Vector3(1f, 0f, 1f)), this, ItemType("VioletForceFieldDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("PinkForceField", "ArmorForceField", new Vector3(1f, 0.1f, 0.5f)), this, ItemType("PinkForceFieldDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrownForceField", "ArmorForceField", new Vector3(0.4f, 0.2f, 0f)), this, ItemType("BrownForceFieldDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("SilverForceField", "ArmorForceField", new Vector3(1f, 1f, 1f)), this, ItemType("SilverForceFieldDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BlackForceField", "ArmorForceField", new Vector3(0.6f, 0.6f, 0.6f)), this, ItemType("BlackForceFieldDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("ShiftingRainbowForceField", "ArmorForceField", 0, 0), this, ItemType("ShiftingRainbowForceFieldDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("ForceField", "ArmorForceField", new Vector3(0f, 2f, 3f)), this, ItemType("ForceFieldDye"));
				//- loki(aura) -//
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("RedAura", "ArmorLoki", new Vector3(1f, 0f, 0f)), this, ItemType("RedAuraDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("OrangeAura", "ArmorLoki", new Vector3(1f, 0.5f, 0f)), this, ItemType("OrangeAuraDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("YellowAura", "ArmorLoki", new Vector3(1f, 1f, 0f)), this, ItemType("YellowAuraDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("LimeAura", "ArmorLoki", new Vector3(0.5f, 1f, 0f)), this, ItemType("LimeAuraDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("GreenAura", "ArmorLoki", new Vector3(0f, 1f, 0f)), this, ItemType("GreenAuraDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("TealAura", "ArmorLoki", new Vector3(0f, 1f, 0.5f)), this, ItemType("TealAuraDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("CyanAura", "ArmorLoki", new Vector3(0f, 1f, 1f)), this, ItemType("CyanAuraDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("SkyBlueAura", "ArmorLoki", new Vector3(0.2f, 0.5f, 1f)), this, ItemType("SkyBlueAuraDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BlueAura", "ArmorLoki", new Vector3(0f, 0f, 1f)), this, ItemType("BlueAuraDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("PurpleAura", "ArmorLoki", new Vector3(0.5f, 0f, 1f)), this, ItemType("PurpleAuraDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("VioletAura", "ArmorLoki", new Vector3(1f, 0f, 1f)), this, ItemType("VioletAuraDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("PinkAura", "ArmorLoki", new Vector3(1f, 0.1f, 0.5f)), this, ItemType("PinkAuraDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrownAura", "ArmorLoki", new Vector3(0.4f, 0.2f, 0f)), this, ItemType("BrownAuraDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("SilverAura", "ArmorLoki", new Vector3(1f, 1f, 1f)), this, ItemType("SilverAuraDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BlackAura", "ArmorLoki", new Vector3(0.2f, 0.2f, 0.2f)), this, ItemType("BlackAuraDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardRainbowShiftingShader("ShiftingRainbowAura", "ArmorLoki", 0, 0), this, ItemType("ShiftingRainbowAuraDye"));
				//- miasma/devil's flame -//
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("RedDevilsFlame", "ArmorHades", new Vector3(2.2f, 1f, 1f), new Vector3(0f, -1f, -1f)), this, ItemType("RedDevilsFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("OrangeDevilsFlame", "ArmorHades", new Vector3(2.2f, 1.5f, 1f), new Vector3(0f, -0.5f, -1f)), this, ItemType("OrangeDevilsFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("YellowDevilsFlame", "ArmorHades", new Vector3(2.2f, 2.2f, 1f), new Vector3(0f, 0f, -1f)), this, ItemType("YellowDevilsFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("LimeDevilsFlame", "ArmorHades", new Vector3(1.5f, 2.2f, 1f), new Vector3(-0.5f, 0f, -1f)), this, ItemType("LimeDevilsFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("GreenDevilsFlame", "ArmorHades", new Vector3(1f, 2.2f, 1f), new Vector3(-1f, 0f, -1f)), this, ItemType("GreenDevilsFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("TealDevilsFlame", "ArmorHades", new Vector3(1f, 2.2f, 1.5f), new Vector3(-1f, 0f, -0.5f)), this, ItemType("TealDevilsFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("CyanDevilsFlame", "ArmorHades", new Vector3(1f, 2.2f, 2.2f), new Vector3(-1f, 0f, 0f)), this, ItemType("CyanDevilsFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("SkyBlueDevilsFlame", "ArmorHades", new Vector3(1.2f, 1.5f, 2.2f), new Vector3(-1f, -0.5f, -0.2f)), this, ItemType("SkyBlueDevilsFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BlueDevilsFlame", "ArmorHades", new Vector3(1f, 1f, 2.2f), new Vector3(-1f, -1f, 0f)), this, ItemType("BlueDevilsFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("PurpleDevilsFlame", "ArmorHades", new Vector3(1.5f, 1f, 2.2f), new Vector3(-0.5f, -1f, 0f)), this, ItemType("PurpleDevilsFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("VioletDevilsFlame", "ArmorHades", new Vector3(2.2f, 1f, 2.2f), new Vector3(0f, -1f, 0f)), this, ItemType("VioletDevilsFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("PinkDevilsFlame", "ArmorHades", new Vector3(2.2f, 1.1f, 1.5f), new Vector3(-0.1f, -1f, -0.5f)), this, ItemType("PinkDevilsFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BrownDevilsFlame", "ArmorHades", new Vector3(1.4f, 1.2f, 1f), new Vector3(0f, -0.3f, -0.5f)), this, ItemType("BrownDevilsFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("BlackDevilsFlame", "ArmorHades", new Vector3(1.6f, 1.6f, 1.6f), new Vector3(-1f, -1f, -1f)), this, ItemType("BlackDevilsFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("SilverDevilsFlame", "ArmorHades", new Vector3(2.2f, 2.2f, 2.2f), new Vector3(-0.6f, -0.6f, -0.6f)), this, ItemType("SilverDevilsFlameDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardShader("QuinesMiasma", "ArmorHades", new Vector3(0.2f, 0.5f, 1f), new Vector3(-5f, 0f, 0f)), this, ItemType("QuinesMiasma"));
				//- special -//
				ShaderLoader.AddModArmorShaderData(new DyeHardSpecialShader("Biome", "ArmorColored", 1.2f, 5), this, ItemType("BiomeDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardSpecialShader("Depth", "ArmorColored", 1.2f, 2), this, ItemType("DepthDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardSpecialShader("Life", "ArmorColored", 1.2f, 0), this, ItemType("LifeDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardSpecialShader("GoldenLife", "ArmorColored", new Vector3(1.17f, 0.75f, 0.24f), 1.2f, 0), this, ItemType("GoldenLifeDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardSpecialShader("BlueLife", "ArmorColored", new Vector3(0f, 0f, 0.92f), 1.2f, 0), this, ItemType("BlueLifeDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardSpecialShader("GreenLife", "ArmorColored", new Vector3(0f, 0.92f, 0f), 1.2f, 0), this, ItemType("GreenLifeDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardSpecialShader("Mana", "ArmorColored", 1.2f, 1), this, ItemType("ManaDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardSpecialShader("GreenMana", "ArmorColored", new Vector3(0.7f, 1f, 0.8f), 1.2f, 1), this, ItemType("GreenManaDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardSpecialShader("RedMana", "ArmorColored", new Vector3(1f, 0.8f, 0.7f), 1.2f, 1), this, ItemType("RedManaDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardSpecialShader("Money", "ArmorColored", 1.2f, 3), this, ItemType("MoneyDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardSpecialShader("Speed", "ArmorColored", new Vector3(0.6f, 0.6f, 0.6f), 1.2f, 7), this, ItemType("SpeedDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardSpecialShader("Time", "ArmorColored", 1.2f, 4), this, ItemType("TimeDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardDemonShader("DemonFire", "ArmorColored", 1.2f, 0, false), this, ItemType("DemonFireDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardDemonShader("CrystalShine", "ArmorColored", 1.2f, 1, false), this, ItemType("CrystalShineDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardDemonShader("StarLight", "ArmorColored", 1.2f, 2, false), this, ItemType("StarLightDye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardDemonShader("DeterminedHeart", "ArmorColored", 1.2f, 3, false), this, ItemType("DeterminedHeartDye"));
				//- player -//
				ShaderLoader.AddModArmorShaderData(new DyeHardPlayerShader("FamiliarHair", "ArmorColored", 1.2f, 0), this, ItemType("FamiliarDyeHair"));
				ShaderLoader.AddModArmorShaderData(new DyeHardPlayerShader("FamiliarEye", "ArmorColored", 1.2f, 1), this, ItemType("FamiliarDyeEye"));
				ShaderLoader.AddModArmorShaderData(new DyeHardPlayerShader("FamiliarSkin", "ArmorColored", 1.2f, 2), this, ItemType("FamiliarDyeSkin"));
				ShaderLoader.AddModArmorShaderData(new DyeHardPlayerShader("FamiliarShirt", "ArmorColored", 1.2f, 3), this, ItemType("FamiliarDyeShirt"));
				ShaderLoader.AddModArmorShaderData(new DyeHardPlayerShader("FamiliarUndershirt", "ArmorColored", 1.2f, 4), this, ItemType("FamiliarDyeUndershirt"));
				ShaderLoader.AddModArmorShaderData(new DyeHardPlayerShader("FamiliarPants", "ArmorColored", 1.2f, 5), this, ItemType("FamiliarDyePants"));
				ShaderLoader.AddModArmorShaderData(new DyeHardPlayerShader("FamiliarShoe", "ArmorColored", 1.2f, 6), this, ItemType("FamiliarDyeShoe"));
			}
		}
	}
}